### ISSUE TITLE
Class Name Error in Comment of 2nd Example (should be "helpful-hint class)

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/introduction-to-css#7]
Type selectors documentation

The element type class is a commonly used selector. Class selectors are used to select all elements that share a given class name. The class selector syntax is: .classname. Prefix the class name with a '.'(period).

/*
select all elements that have the 'important-topic' classname (e.g. <h1 class='important-topic'>
and <h1 class='important-topic'>)
*/
.important-topic
 
/*
select all elements that have the 'welcome-message' classname (e.g. <p class='helpful-hint'>
and <p class='helpful-hint'>)
*/
.helpful-hint

**Comment by sgharms** [comment]
Thanks! All fixed.
