### ISSUE TITLE
Simple typos in README.md

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/introduction-to-css#9]
Line 41 reads:

* Does this menu belong in in the navigation in the header?

Should be:

* Does this menu belong in the navigation in the header?

Line 44-45 reads:

These questions deal with structure, hierarchy, and meaning, which are
are concerns of the content layer (HTML).

Should be:

These questions deal with structure, hierarchy, and meaning, which are
concerns of the content layer (HTML).

Line 89 reads:

selector syntax may be `html` or `body`. For anchors, you selector would be

Should be:

selector syntax may be `html` or `body`. For anchors, your selector would be

**Comment by jenmyers** [comment]
Resolved.
